FROM --platform=${TARGETPLATFORM} golang:1.24.3-alpine3.22 as build

WORKDIR /workspace/bin
COPY ./bin ./

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then mv manager.linux.amd64 manager; fi
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then mv manager.linux.arm64 manager; fi

FROM --platform=$TARGETPLATFORM gcr.io/distroless/static:nonroot
COPY --from=build /workspace/bin/manager /manager

USER 65532:65532
ENTRYPOINT ["/manager"]