---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-monitoring-whatap-com-v2alpha1-whatapagent
  failurePolicy: Fail
  name: mwhatapagent-v2alpha1.kb.io
  rules:
  - apiGroups:
    - monitoring.whatap.com
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - whatapagents
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-whatap-com-v2alpha1-whatapagent
  failurePolicy: Fail
  name: vwhatapagent-v2alpha1.kb.io
  rules:
  - apiGroups:
    - monitoring.whatap.com
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - whatapagents
  sideEffects: None
