---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: whatap-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: whatap-admission-controller
      namespace: <WHATAP_DEFUALT_NAMESPACE>
      path: /mutate-monitoring-whatap-com-v2alpha1-whatapagent
  failurePolicy: Fail
  name: mwhatapagent-v2alpha1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: whatap-admission-controller
      namespace: default
      path: /validate-monitoring-whatap-com-v2alpha1-whatapagent
  failurePolicy: Fail
  name: vwhatapagent-v2alpha1.kb.io
  rules:
  - apiGroups:
    - monitoring.whatap.com
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - whatapagents
  sideEffects: None
