apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: whatap-operator
    app.kubernetes.io/managed-by: kustomize
  name: whatap-admission-controller
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: whatap-operator
