# permissions for end users to edit whatapagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: whatap-operator
    app.kubernetes.io/managed-by: kustomize
  name: whatapagent-editor-role
rules:
- apiGroups:
  - monitoring.whatap.com
  resources:
  - whatapagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.whatap.com
  resources:
  - whatapagents/status
  verbs:
  - get
