apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap-sample
spec:
  license: "your-license-key"
  host: "whatap-server"
  port: "6600"
  image: "whatap/operator:0.2.0"
  features:
    apm:
      instrumentation:
        targets:
          - name: "shop-api"
            enabled: "true"
            whatapApmVersions:
              java: "latest"
            namespaceSelector:
              matchNames:
                - "backend"
              matchLabels:
                environment: "production"
              matchExpressions:
                - {key: tier, operator: In, values: [frontend, backend]}
            podSelector:
              matchLabels:
                app: "shop"
              matchExpressions:
                - {key: tier, operator: In, values: [backend, backend2, backend3]}
                - {key: environment, operator: NotIn, values: [dev, test]}
            config:
              configMap:
                name: "shop-api-config"
                namespace: "backend"
    openAgent:
      enabled: true
      targets:
        - targetName: "kube-apiserver"
          type: "ServiceMonitor"
          namespaceSelector:
            matchNames:
              - "default"
          selector:
            component: "apiserver"
            provider: "kubernetes"
          endpoints:
            - port: "https"
              path: "/metrics"
              interval: "30s"
              scheme: "https"
              tlsConfig:
                insecureSkipVerify: true
          metricRelabelConfigs:
            - source_labels: ["__name__"]
              regex: "apiserver_request_total"
              action: "keep"
            - source_labels: ["verb"]
              target_label: "http_verb"
              replacement: "${1}"
              action: "replace"
            - target_label: "metric_src"
              replacement: "whatap-open-agent"
              action: "replace"
