apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap-sample
spec:
  license: "your-license-key"
  host: "whatap-server"
  port: "6600"
  image: "whatap/operator:0.2.0"
  features:
    apm:
      instrumentation:
        targets:
          - name: "shop-api"
            enabled: "true"
            whatapApmVersions:
              java: "latest"
            namespaceSelector:
              matchNames:
                - "backend"
              matchLabels:
                environment: "production"
              matchExpressions:
                - {key: tier, operator: In, values: [frontend, backend]}
            podSelector:
              matchLabels:
                app: "shop"
              matchExpressions:
                - {key: tier, operator: In, values: [backend, backend2, backend3]}
                - {key: environment, operator: NotIn, values: [dev, test]}
            config:
              configMap:
                name: "shop-api-config"
                namespace: "backend"
