apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  # Secret에서 자동으로 가져옴 (권장 방식)
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "python-fastapi"
            enabled: true
            language: "python"
            whatapApmVersions:
              python: "1.8.5"
            podSelector:
              matchLabels:
                app: "python-app"
            namespaceSelector:
              matchNames:
                - "default"
            # Python Agent 상세 설정 (선택 사항)
            envs:
              # 애플리케이션 이름 설정 (기본값: 컨테이너 이름)
              - name: "app_name"
                value: "custom-python-service"
              # 애플리케이션 프로세스 이름 설정
              - name: "app_process_name"
                value: "gunicorn"
              # OKIND 설정 (애플리케이션 종류 그룹화)
              - name: "OKIND"
                value: "API_SERVER_GROUP"