apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  # Secret에서 자동으로 가져옴 (권장 방식)
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "python-fastapi"
            enabled: true
            language: "python"
            whatapApmVersions:
              python: "1.8.5"
            podSelector:
              matchLabels:
                app: "python-app"
            namespaceSelector:
              matchNames:
                - "default"