apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    ### APM 자동 설치 사용시 주석 해제 - APM 에이전트를 애플리케이션 Pod에 자동으로 주입하여 애플리케이션 성능 모니터링을 활성화합니다.
    # apm:
    #   instrumentation:
    #     targets:
    #       - name: hello-world
    #         enabled: true
    #         language: "java"          # 지원 언어: java, python, php, dotnet, nodejs, golang
    #         whatapApmVersions:
    #           java: "2.2.58"          # 사용할 APM 에이전트 버전
    #         namespaceSelector:
    #           matchNames:
    #             - default             # 모니터링할 애플리케이션이 있는 네임스페이스
    #         podSelector:
    #           matchLabels:
    #             app: "hello-world"    # 모니터링할 애플리케이션 Pod의 라벨
    #         config:
    #           mode: default           # APM 에이전트 모드 설정
    
    ### K8s 모니터링시 주석 해제 - Kubernetes 클러스터, 노드, 컨테이너 모니터링을 활성화합니다.
    # k8sAgent:
    #   masterAgent:
    #     enabled: true                 # 마스터 에이전트 활성화 (클러스터 수준 메트릭 수집)
    #   nodeAgent:
    #     enabled: true                 # 노드 에이전트 활성화 (노드 및 컨테이너 수준 메트릭 수집)
    
    ### 오픈메트릭(프로메테우스 형태의 지표수집) 사용 시 주석 해제 - Prometheus 형식의 메트릭을 수집합니다.
    # openAgent:
    #     enabled: true                 # OpenAgent 활성화
    #     globalInterval: "60s"         # 기본 스크래핑 간격
    #     globalPath: "/metrics"        # 기본 메트릭 경로
    #     targets:
    #       - targetName: kube-apiserver
    #         type: ServiceMonitor      # 대상 유형: ServiceMonitor, PodMonitor, StaticEndpoints
    #         namespaceSelector:
    #           matchNames:
    #             - "default"           # 메트릭을 수집할 네임스페이스
    #         selector:
    #           matchLabels:
    #             component: apiserver  # 메트릭을 수집할 서비스/Pod의 라벨
    #             provider: kubernetes
    #         endpoints:
    #           - port: "https"         # 메트릭 엔드포인트 포트
    #             path: "/metrics"      # 메트릭 경로
    #             interval: "30s"       # 이 엔드포인트의 스크래핑 간격
    #             scheme: "https"       # HTTP 스키마 (http 또는 https)
    #             tlsConfig:
    #               insecureSkipVerify: true  # TLS 인증서 검증 건너뛰기
    #         metricRelabelConfigs:
    #           - source_labels: ["__name__"]
    #             regex: "apiserver_request_total"  # 수집할 메트릭 필터링
    #             action: "keep"                    # 일치하는 메트릭만 유지
    
    ### GPU 모니터링 사용 시 주석 해제 - NVIDIA GPU 메트릭 수집을 활성화합니다.
    # gpuMonitoring:
    #     enabled: true                 # GPU 모니터링 활성화 (NVIDIA DCGM 기반)