#!/usr/bin/env bash
set -euo pipefail

# Export/copy the Python standalone sample app to a separate project directory.
# Default target: /Users/jaeyoung/work/python-standalone
# Usage:
#   scripts/export-python-standalone.sh [TARGET_DIR]
#
# Example:
#   scripts/export-python-standalone.sh /Users/jaeyoung/work/python-standalone

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$ROOT_DIR/examples/python-standalone-sample"
TARGET_DIR="${1:-/Users/jaeyoung/work/python-standalone}"

if [[ ! -d "$SRC_DIR" ]]; then
  echo "[export] Source directory not found: $SRC_DIR" >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"

# List of files to export (explicit to keep it minimal)
FILES=(
  "app_single.py"
  "app_multi.py"
)

echo "[export] Exporting Python standalone sample to: $TARGET_DIR"

for f in "${FILES[@]}"; do
  if [[ -f "$SRC_DIR/$f" ]]; then
    cp "$SRC_DIR/$f" "$TARGET_DIR/"
    echo "[export] Copied $f"
  fi
done

# Also create a minimal README with run instructions if missing
README_TGT="$TARGET_DIR/README.md"
if [[ ! -f "$README_TGT" ]]; then
  cat > "$README_TGT" <<'EOF'
# Python Standalone Sample (exported)

This folder contains the Python standalone sample files exported from whatap-operator/examples/python-standalone-sample.

## Files
- app_single.py: single-transaction sample
- app_multi.py: multiple-transaction sample

## Quick start
Create a venv (optional) and run the samples. If you plan to test with Whatap Python agent in standalone mode, set the below envs accordingly and launch via whatap-start-agent.

```bash
# (optional) python venv
python3 -m venv .venv && source .venv/bin/activate
pip install --upgrade pip

# Run without agent (plain Python)
python app_single.py
python app_multi.py

# Example with Whatap standalone agent (assuming your environment has whatap-start-agent available)
# Single-transaction
STANDALONE_ENABLED=true whatap-start-agent app_single.py

# Multiple-transaction
STANDALONE_ENABLED=true \
STANDALONE_TYPE=multiple-transaction \
STANDALONE_TRANSACTION_PATTERNS="__main__:task_alpha,__main__:Worker.run" \
whatap-start-agent app_multi.py
```

If you use the provided Whatap Python agent container, ensure your whatap.conf is present or generated by the container entrypoint.
EOF
  echo "[export] Generated README.md"
fi

echo "[export] Done."
