apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    k8sAgent:
      masterAgent:
        enabled: true
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "500m"
            memory: "600Mi"
      nodeAgent:
        enabled: true
        resources:
          requests:
            cpu: "150m"
            memory: "350Mi"
          limits:
            cpu: "300m"
            memory: "500Mi"

# 참고: 시크릿 기반 자격 증명 사용 시 다음 명령으로 시크릿을 생성하세요:
# kubectl create secret generic whatap-credentials --namespace whatap-monitoring \
#   --from-literal=license=$WHATAP_LICENSE \
#   --from-literal=host=$WHATAP_HOST \
#   --from-literal=port=$WHATAP_PORT
