apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    apm:
      instrumentation:
        targets: []
    openAgent:
      enabled: false
    k8sAgent:
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true
      apiserverMonitoring:
        enabled: false
      etcdMonitoring:
        enabled: false
      schedulerMonitoring:
        enabled: false
      gpuMonitoring:
        enabled: false
