apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    k8sAgent:
      masterAgent:
        enabled: true
        # Tolerations for the master agent
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
          - key: "special-workload"
            operator: "Exists"
            effect: "NoSchedule"
      nodeAgent:
        enabled: true
        # Tolerations for the node agent
        # Note: These are in addition to the default tolerations for master and control-plane nodes
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
          - key: "gpu"
            operator: "Exists"
            effect: "NoSchedule"

# 참고: 시크릿 기반 자격 증명 사용 시 다음 명령으로 시크릿을 생성하세요:
# kubectl create secret generic whatap-credentials --namespace whatap-monitoring \
#   --from-literal=license=$WHATAP_LICENSE \
#   --from-literal=host=$WHATAP_HOST \
#   --from-literal=port=$WHATAP_PORT

# Note: The WhatapAgent CR now directly supports specifying tolerations.
# The tolerations specified in the CR will be applied to the respective pods.
# For the node agent, the specified tolerations are added to the default tolerations
# for master and control-plane nodes.
#
# Default tolerations for the node agent:
# - key: "node-role.kubernetes.io/master", effect: "NoSchedule"
# - key: "node-role.kubernetes.io/control-plane", effect: "NoSchedule"
