apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  license: "x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502"
  host: "15.165.146.117"
  port: "6600"
  features:
    openAgent:
        enabled: true
        globalInterval: "60s"
        globalPath: "/metrics"
        # Custom image name and version for OpenAgent
        imageName: "custom-registry.example.com/whatap/open_agent"
        imageVersion: "v1.2.3"
        targets:
          - targetName: kube-apiserver
            type: ServiceMonitor
            # This target is enabled (default is true if not specified)
            enabled: true
            namespaceSelector:
              matchNames:
                - "default"
            selector:
              matchLabels:
                component: apiserver
                provider: kubernetes
            endpoints:
              - port: "https"
                path: "/metrics"
                interval: "30s"
                scheme: "https"
                tlsConfig:
                  insecureSkipVerify: true
            metricRelabelConfigs:
              - source_labels: ["__name__"]
                regex: "apiserver_request_total"
                action: "keep"

          # Example of a disabled target
          - targetName: node-exporter
            type: PodMonitor
            # This target is disabled and will be skipped
            enabled: false
            namespaceSelector:
              matchNames:
                - "monitoring"
            selector:
              matchLabels:
                app: "node-exporter"
            endpoints:
              - port: "metrics"
                path: "/metrics"
                interval: "30s"
