apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  # No license, host, or port specified here
  # These values will be retrieved from the "whatap-credentials" secret
  features:
    k8sAgent:
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true

# Create the secret with the following command:
# kubectl create secret generic whatap-credentials --namespace whatap-monitoring \
#   --from-literal=license=$WHATAP_LICENSE \
#   --from-literal=host=$WHATAP_HOST \
#   --from-literal=port=$WHATAP_PORT