apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    apm:
      instrumentation:
        targets:
          - name: hello-world
            enabled: true
            language: "java"
            whatapApmVersions:
              java: "2.2.58"
            namespaceSelector:
              matchNames:
                - default
            podSelector:
              matchLabels:
                app: "hello-world"
            config:
              mode: default
    openAgent:
      enabled: false
    k8sAgent:
      masterAgent:
        enabled: false
      nodeAgent:
        enabled: false
      apiserverMonitoring:
        enabled: false
      etcdMonitoring:
        enabled: false
      schedulerMonitoring:
        enabled: false
      gpuMonitoring:
        enabled: false

# 참고: 시크릿 기반 자격 증명 사용 시 다음 명령으로 시크릿을 생성하세요:
# kubectl create secret generic whatap-credentials --namespace whatap-monitoring \
#   --from-literal=license=$WHATAP_LICENSE \
#   --from-literal=host=$WHATAP_HOST \
#   --from-literal=port=$WHATAP_PORT
