apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  license: "x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502"
  host: "15.165.146.117"
  port: "6600"
  features:
    k8sAgent:
      # Custom agent image name
      agentImageName: "my-registry.example.com/whatap/kube_agent"
      # Custom agent image version
      agentImageVersion: "v1.2.3"
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true