apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    # APM configuration with custom image and additional arguments
    apm:
      instrumentation:
        targets:
          - name: "java-app"
            enabled: true
            language: "java"
            whatapApmVersions:
              java: "2.2.58"
            # Custom image name for APM agent
            customImageName: "my-registry.example.com/whatap/apm-init-java:2.2.58"
            # Additional arguments for APM agent
            additionalArgs:
              "whatap.app.name": "my-java-app"
              # 참고: license와 host는 시크릿을 통해 설정하는 것을 권장합니다
            namespaceSelector:
              matchNames:
                - "default"
            podSelector:
              matchLabels:
                app: "java-app"
            config:
              mode: "default"

    k8sAgent:
      # Custom agent image name for Kubernetes agent
      agentImageName: "my-registry.example.com/whatap/kube_agent"
      # Custom agent image version for Kubernetes agent
      agentImageVersion: "v1.2.3"
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true

    # OpenAgent configuration with custom image
    openAgent:
      enabled: true
      # Custom image name for OpenAgent
      imageName: "my-registry.example.com/whatap/open_agent"
      # Custom image version for OpenAgent
      imageVersion: "v1.2.3"
      globalInterval: "60s"
      globalPath: "/metrics"

# 참고: 시크릿 기반 자격 증명 사용 시 다음 명령으로 시크릿을 생성하세요:
# kubectl create secret generic whatap-credentials --namespace whatap-monitoring \
#   --from-literal=license=$WHATAP_LICENSE \
#   --from-literal=host=$WHATAP_HOST \
#   --from-literal=port=$WHATAP_PORT
