apiVersion: monitoring.whatap.com/v2alpha1
kind: WhatapAgent
metadata:
  name: whatap
spec:
  features:
    apm:
      instrumentation:
        targets:
          - name: hello-world
            enabled: true
            language: "java"
            whatapApmVersions:
              java: "2.2.58"
            namespaceSelector:
              matchNames:
                - default
            podSelector:
              matchLabels:
                app: "hello-world"
            config:
              mode: default
    openAgent:
      enabled: false
    k8sAgent:
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true
      apiserverMonitoring:
        enabled: false
      etcdMonitoring:
        enabled: false
      schedulerMonitoring:
        enabled: false
      gpuMonitoring:
        enabled: false
